name: fastly-grafana
proxy:
  grafana:
    - grafana.lndo.site:3000
services:
  database:
    type: mariadb
    portforward: 32769
    creds:
      user: fastly
      password: fastly
      database: fastly
  cache:
    type: redis
    persist: false
    portforward: 6379
  grafana:
    type: compose
    services:
      image: grafana/grafana
      user: grafana
      ports: [3000:3000]
      environment:
        GF_INSTALL_PLUGINS: grafana-piechart-panel
        GF_AUTH_DISABLE_LOGIN_FORM: "true"
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      # Required (entry point for Grafana container)
      command: /run.sh
      build: ./grafana
