name: fastly-grafana
proxy:
  grafana:
    - grafana.lndo.site:3000
services:
  database:
    type: mysql
    portforward: 32769
    creds:
      user: fastly
      password: fastly
      database: fastly
  grafana:
    type: compose
    services:
      image: grafana/grafana
      user: grafana
      ports: [3000:3000]
      environment:
        GF_INSTALL_PLUGINS: grafana-piechart-panel
      # Required (entry point for Grafana container)
      command: /run.sh
