{
 "title": "Fastly Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db_table", "label": "Database Table", "query": "fastly" }
  ]
 },
 "panels": [
  {
   "title": "Total Visitors",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT CONCAT(ip,user_agent)) AS visitors_count FROM fastly;"
    }
   ]
  },
  {
   "title": "Pages Served",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT COUNT(url) AS pages_served_count FROM fastly;"
    }
   ]
  },
  {
   "title": "Top 100 Requests",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT DISTINCT SUBSTRING_INDEX(url,'?', 1) AS resource, COUNT(SUBSTRING_INDEX(url,'?', 1)) AS resource_count, now() as time_sec FROM fastly GROUP BY SUBSTRING_INDEX(url,'?', 1) ORDER BY resource_count DESC limit 100;"
    }
   ]
  },
  {
   "title": "Top 100 IPs",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT now() as time_sec, ip, COUNT(ip) AS ip_count FROM fastly GROUP BY ip ORDER BY ip_count DESC limit 100;"
    }
   ]
  },
  {
   "title": "Top 100 User Agents",
   "type": "grafana-piechart-panel",
   "description": "Break down by unique user agents.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT DISTINCT user_agent, COUNT(user_agent) AS user_agent_count, now() as time_sec FROM fastly GROUP BY user_agent ORDER BY user_agent_count DESC limit 100;"
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "table",
   "description": "Break down by unique user agents.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT user_agent, COUNT(user_agent) AS user_agent_count FROM fastly GROUP BY user_agent ORDER BY user_agent_count DESC;"
    }
   ]
  },
  {
   "title": "Unique Requests (Clean Params)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT SUBSTRING_INDEX(url,'?', 1) AS resource, COUNT(SUBSTRING_INDEX(url,'?', 1)) AS resource_count FROM fastly GROUP BY SUBSTRING_INDEX(url,'?', 1) ORDER BY resource_count DESC;"
    }
   ]
  },
  {
   "title": "WP Vector IPs",
   "type": "table",
   "description": "Detects wp-login and xmlrpc",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT ip, COUNT(ip) AS ip_count FROM fastly WHERE url LIKE '/wp-login.php%' or url like '/xmlrpc%' GROUP BY ip ORDER BY ip_count DESC;"
    }
   ]
  },
  {
   "title": "Feeds and Scripts",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT url, COUNT(url) AS ip_count FROM fastly WHERE url LIKE '%.php%' or url LIKE '%xml%' or url LIKE '%json%' GROUP BY url ORDER BY ip_count DESC;"
    }
   ]
  },
  {
   "title": "Unique Requests (expanded)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT url, COUNT(url) AS url_served_count FROM fastly GROUP BY url ORDER BY url_served_count DESC;"
    }
   ]
  }
 ]
}